---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maxscale
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0%
      maxSurge: 66%
  revisionHistoryLimit: 5
  replicas: 3
  template:
    metadata:
      labels:
        tier: db
        app: maxscale
    spec:
      volumes:
        - name: maxscale-cnf
          configMap:
            name: maxscale-cnf
      containers:
        - name: maxscale
          image: mariadb/maxscale:2.2.13
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: maxscale-cnf
          volumeMounts:
            - name: maxscale-cnf
              mountPath: /etc/maxscale.cnf
              subPath: maxscale.cnf
          ports:
            - containerPort: 3306
            - containerPort: 6033
          resources:
            limits:
              cpu: 200m
              memory: 768Mi
            requests:
              cpu: 200m
              memory: 768Mi
          env:
            - name: APPLICATION_ID
              value: maxscale
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
        - name: maxscale-exporter
          image: lvejm/maxscale_exporter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9195
          resources:
            limits:
              cpu: 50m
              memory: 25Mi
        - name: prometheus-to-sd
          image: gcr.io/google-containers/prometheus-to-sd:v0.5.0
          command:
            - /monitor
            - --source=:http://localhost:9195
            - --stackdriver-prefix=custom.googleapis.com
            - --pod-id=$(POD_ID)
            - --namespace-id=$(POD_NAMESPACE)
          resources:
            limits:
              cpu: 50m
              memory: 25Mi
          env:
            - name: POD_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.uid
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

